---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot


Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'