---
volumes:
  bundle:
  yarn:
  postgres:
  redis:

services:
  app:
    image: ghcr.io/demsullivan/unthread-development
    build:
      context: .
    command: [ "bash", "-c", "bundle exec puma -C config/puma.rb" ]
    env_file:
      - .env.development
    volumes:
      - .:/app
      - bundle:/bundle
      - yarn:/app/node_modules
    tmpfs: /app/tmp/pids
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis

  vite:
    image: ghcr.io/demsullivan/unthread-development
    env_file:
      - .env.development
    volumes:
      - .:/app
      - bundle:/bundle
      - yarn:/app/node_modules
    depends_on:
      - app
    command: ["bash", "-c", "./bin/vite dev"]
    ports:
      - 3036:3036

  postgres:
    image: postgres:16
    restart: 'no'
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      POSTGRES_DBS: unthread_development,unthread_test
      POSTGRES_EXTENSIONS: pgcrypto
      DATABASE_NAME_DEV: unthread_development
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/pg_scripts:/docker-entrypoint-initdb.d
    
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
